-------------------------------------------------------------------------------
Test set: com.portfolio.api.ApiApplicationTests
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.265 s <<< FAILURE! - in com.portfolio.api.ApiApplicationTests
contextLoads  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.jdbc.datasource.init.UncategorizedScriptException: Failed to execute database script; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLSyntaxErrorException: User 'uh8wq0snmf33ksqh' has exceeded the 'max_user_connections' resource (current value: 5)
Caused by: org.springframework.jdbc.datasource.init.UncategorizedScriptException: Failed to execute database script; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLSyntaxErrorException: User 'uh8wq0snmf33ksqh' has exceeded the 'max_user_connections' resource (current value: 5)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLSyntaxErrorException: User 'uh8wq0snmf33ksqh' has exceeded the 'max_user_connections' resource (current value: 5)
Caused by: java.sql.SQLSyntaxErrorException: User 'uh8wq0snmf33ksqh' has exceeded the 'max_user_connections' resource (current value: 5)

